namespace VulTrack.App;

public static class AdminEndpoints
{
    public static WebApplication MapAdminEndpoints(this WebApplication app)
    {
        app.MapGet("/api/v1/admin.source.list", (HttpContext context, AdminAuthService auth, VulTrackOptions options) =>
        {
            if (!auth.IsAuthenticated(context)) return ApiResult.Unauthorized();
            return ApiResult.Ok(SourceEndpoints.DuckDbConfiguredSources(options));
        });

        app.MapPost("/api/v1/admin.source.fetch", async (HttpContext context, AdminAuthService auth, DuckDbFirstScheduler scheduler, DuckDbSourceFetchRequest request, CancellationToken ct) =>
        {
            if (!auth.IsAuthenticated(context)) return ApiResult.Unauthorized();
            if (string.IsNullOrWhiteSpace(request.SourceCode))
                return ApiResult.Error("SOURCE_REQUIRED", "sourceCode is required.");
            await scheduler.RunSourceAsync(request.SourceCode.Trim(), request.Force, request.Limit, ct);
            return ApiResult.Ok(new { sourceCode = request.SourceCode.Trim(), request.Force, request.Limit });
        });

        app.MapPost("/api/v1/admin.duckdbSpool.ingest", async (HttpContext context, AdminAuthService auth, DuckDbEvidenceNormalizer normalizer, DuckDbSpoolIngestRequest request, CancellationToken ct) =>
        {
            if (!auth.IsAuthenticated(context)) return ApiResult.Unauthorized();
            return ApiResult.Ok(await normalizer.IngestSpoolAsync(request, ct));
        });

        app.MapPost("/api/v1/admin.duckdbAi.import", async (HttpContext context, AdminAuthService auth, DuckDbEvidenceStore duckDb, DuckDbAiImportRequest request, CancellationToken ct) =>
        {
            if (!auth.IsAuthenticated(context)) return ApiResult.Unauthorized();
            return ApiResult.Ok(await duckDb.ImportAiAnalysesAsync(request.Path, ct));
        });

        app.MapGet("/api/v1/admin.duckdbEvidence.stats", async (HttpContext context, AdminAuthService auth, DuckDbEvidenceStore store, CancellationToken ct) =>
        {
            if (!auth.IsAuthenticated(context)) return ApiResult.Unauthorized();
            return ApiResult.Ok(await store.StatsAsync(ct));
        });

        app.MapGet("/api/v1/admin.duckdbEvidence.coverage", async (HttpContext context, AdminAuthService auth, DuckDbEvidenceStore store, CancellationToken ct) =>
        {
            if (!auth.IsAuthenticated(context)) return ApiResult.Unauthorized();
            return ApiResult.Ok(await store.CoverageStatusAsync(ct));
        });

        app.MapPost("/api/v1/admin.duckdbCatalog.rebuild", async (HttpContext context, AdminAuthService auth, DuckDbEvidenceStore store, CancellationToken ct) =>
        {
            if (!auth.IsAuthenticated(context)) return ApiResult.Unauthorized();
            return ApiResult.Ok(await store.RebuildCatalogAsync(ct));
        });

        app.MapPost("/api/v1/admin.vulnerability.aiSummary", async (HttpContext context, AdminAuthService auth, DuckDbEvidenceStore duckDb, AiSummaryRequest request, CancellationToken ct) =>
        {
            if (!auth.IsAuthenticated(context)) return ApiResult.Unauthorized();
            var cached = await duckDb.GetAiAnalysisAsync(request.Id, ct);
            return cached is null
                ? ApiResult.Error("AI_BATCH_REQUIRED", "DuckDB-primary AI analyses are generated by the standalone batch process and then imported.")
                : ApiResult.Ok(cached);
        });

        app.MapGet("/api/v1/admin.vulnerability.aiSummaryInput", async (HttpContext context, AdminAuthService auth, DuckDbEvidenceStore duckDb, Guid id, CancellationToken ct) =>
        {
            if (!auth.IsAuthenticated(context)) return ApiResult.Unauthorized();
            var detail = await duckDb.GetCatalogDetailAsync(id, ct);
            return detail is null ? ApiResult.NotFound("VULNERABILITY_NOT_FOUND", id.ToString()) : ApiResult.Ok(detail);
        });

        return app;
    }
}
